/**
 * T-129: passenger-mode page.
 *
 * The primary beneficiary of Transit-AI is the **tram passenger** in Moscow.
 * Their two pain points are:
 *   1. "When will the next tram arrive?"   → ETA cards
 *   2. "Will there be a free seat?"        → load % on each card
 *
 * This component answers both questions with a single glance: the passenger
 * picks their stop, sees the next 3 trams, and gets a recommendation banner
 * generated by `recommend()` from T-130 (pure function, lives in `lib/`).
 *
 * The data layer (`@/lib/etaClient`) is mocked today and will be swapped to
 * the real backend once T-127 lands. The switch is environment-driven, so
 * the page itself doesn't need to change.
 *
 * T-141: every UI literal in this file is resolved through `t()` / `tf()`
 * from `lib/i18n`. The recommendation `text` itself is still produced by
 * `recommend()` as pure data -- the Russian copy there is the *single
 * source of truth for the recommendation sentence*, and tests assert on
 * it directly. UI labels around that sentence, however, go through `t()`.
 */

import { useEffect, useState } from 'react';

import { t, tf } from '@/lib/i18n/t';

import { Alert } from '@/lib/Alert';
import { fetchActiveModel, formatWapeScore, type ActiveModelInfo } from '@/lib/activeModel';
import { getEta, getStops, type Stop } from '@/lib/etaClient';
import { EtaCard } from '@/lib/EtaCard';
import { recommend, type ETAPrediction } from '@/lib/recommend';

export function PassengerMode(): JSX.Element {
  const [stops, setStops] = useState<Stop[]>([]);
  const [stopId, setStopId] = useState<number | null>(null);
  const [eta, setEta] = useState<ETAPrediction[]>([]);
  const [activeModel, setActiveModel] = useState<ActiveModelInfo | null>(null);
  const [loadingStops, setLoadingStops] = useState(true);
  const [loadingEta, setLoadingEta] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // 1) Load the list of stops once on mount.
  useEffect(() => {
    let cancelled = false;
    setLoadingStops(true);
    getStops()
      .then((list) => {
        if (cancelled) return;
        setStops(list);
        if (list.length > 0 && list[0]) {
          setStopId(list[0].id);
        }
      })
      .catch((e: unknown) => {
        if (cancelled) return;
        setError(e instanceof Error ? e.message : String(e));
      })
      .finally(() => {
        if (!cancelled) setLoadingStops(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  // T-201: load active model from /api/v1/models/active on mount. Failure
  // is silent — the footer just falls back to "Model: <eta[0].model_id>".
  useEffect(() => {
    let cancelled = false;
    fetchActiveModel()
      .then((info) => {
        if (!cancelled) setActiveModel(info);
      })
      .catch(() => {
        // Silent — keep current behaviour (no model badge).
      });
    return () => {
      cancelled = true;
    };
  }, []);

  // 2) Whenever the selected stop changes, fetch its ETA predictions.
  //    Also re-fetch every minute so the data doesn't go stale during a demo.
  useEffect(() => {
    if (stopId === null) return;
    let cancelled = false;
    setLoadingEta(true);
    setError(null);

    const refetch = (): void => {
      getEta(stopId)
        .then((list) => {
          if (cancelled) return;
          setEta(list);
        })
        .catch((e: unknown) => {
          if (cancelled) return;
          setError(e instanceof Error ? e.message : String(e));
        })
        .finally(() => {
          if (!cancelled) setLoadingEta(false);
        });
    };

    refetch();
    const interval = window.setInterval(refetch, 60_000);
    return () => {
      cancelled = true;
      window.clearInterval(interval);
    };
  }, [stopId]);

  // 3) Derive the recommendation from the current ETA list.
  //    `recommend` is pure, so calling it directly inside the render body
  //    is fine — it's cheaper than memoising for an array of at most 3 items.
  const recommendation = recommend(eta);

  // T-201: prefer the active model from /api/v1/models/active (more
  // accurate: backend picks the active artifact), fall back to the
  // model_id from the first ETA prediction if the endpoint is down.
  const activeModelId = activeModel?.model_id ?? eta[0]?.model_id ?? '—';
  const wapeLabel = formatWapeScore(activeModel?.wape_score ?? null);
  const footerText =
    wapeLabel !== null
      ? tf('passenger.activeModelFooter', activeModelId, wapeLabel)
      : tf('passenger.modelFooter', activeModelId);

  return (
    <section style={{ padding: '16px 24px', fontFamily: 'system-ui, sans-serif' }}>
      <h2 style={{ marginTop: 0 }}>{t('passenger.modeTitle')}</h2>
      <p style={{ color: '#666', marginTop: 4 }}>{t('passenger.modeHint')}</p>

      <label htmlFor="stop-select" style={{ display: 'block', marginTop: 16, fontWeight: 600 }}>
        {t('passenger.stopsLabel')}
      </label>
      <select
        id="stop-select"
        value={stopId ?? ''}
        onChange={(e) => setStopId(Number(e.target.value))}
        disabled={loadingStops || stops.length === 0}
        style={{
          marginTop: 4,
          padding: '8px 12px',
          fontSize: 16,
          minWidth: 240,
          border: '1px solid #ccc',
          borderRadius: 4,
          background: '#fff',
        }}
      >
        {loadingStops && <option value="">{t('passenger.stopsLoading')}</option>}
        {!loadingStops && stops.length === 0 && (
          <option value="">{t('passenger.stopsEmpty')}</option>
        )}
        {stops.map((stop) => (
          <option key={stop.id} value={stop.id}>
            {stop.name}
          </option>
        ))}
      </select>

      {error && (
        <Alert severity="warning" icon="⚠️">
          {tf('passenger.etaError', error)}
        </Alert>
      )}

      {loadingEta && stopId !== null && (
        <p style={{ color: '#666' }}>{t('passenger.etaLoading')}</p>
      )}

      {!loadingEta && stopId !== null && (
        <>
          {/* recommend() returns "no data" Recommendation when eta is empty,
              so we render the banner unconditionally for the selected stop. */}
          <Alert severity={recommendation.severity} icon={recommendation.emoji}>
            {recommendation.text}
          </Alert>

          {eta.length > 0 && (
            <>
              <div
                style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
                  gap: 12,
                  marginTop: 16,
                }}
              >
                {eta.map((tram, i) => (
                  // eta_min + route_id together are unique per stop in practice.
                  <EtaCard key={`${tram.route_id}-${tram.eta_min}-${i}`} tram={tram} />
                ))}
              </div>

              <p style={{ marginTop: 16, color: '#888', fontSize: 12 }}>
                {footerText}
              </p>
            </>
          )}
        </>
      )}
    </section>
  );
}
