/**
 * T-129: passenger-mode page.
 *
 * The primary beneficiary of Transit-AI is the **tram passenger** in Moscow.
 * Their two pain points are:
 *   1. "When will the next tram arrive?"   → ETA cards
 *   2. "Will there be a free seat?"        → load % on each card
 *
 * This component answers both questions with a single glance: the passenger
 * picks their stop, sees the next 3 trams, and gets a recommendation banner
 * ("board — comfortable" / "wait — the next one will be lighter" / "it's
 * tight — no better option") generated by `recommend()` from T-130.
 *
 * The data layer (`@/lib/etaClient`) is mocked today and will be swapped to
 * the real backend once T-127 lands. The switch is environment-driven, so
 * the page itself doesn't need to change.
 */

import { useEffect, useState } from 'react';

import { Alert } from '@/lib/Alert';
import { getEta, getStops, type Stop } from '@/lib/etaClient';
import { EtaCard } from '@/lib/EtaCard';
import { recommend, type ETAPrediction } from '@/lib/recommend';

export function PassengerMode(): JSX.Element {
  const [stops, setStops] = useState<Stop[]>([]);
  const [stopId, setStopId] = useState<number | null>(null);
  const [eta, setEta] = useState<ETAPrediction[]>([]);
  const [loadingStops, setLoadingStops] = useState(true);
  const [loadingEta, setLoadingEta] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // 1) Load the list of stops once on mount.
  useEffect(() => {
    let cancelled = false;
    setLoadingStops(true);
    getStops()
      .then((list) => {
        if (cancelled) return;
        setStops(list);
        if (list.length > 0 && list[0]) {
          setStopId(list[0].id);
        }
      })
      .catch((e: unknown) => {
        if (cancelled) return;
        setError(e instanceof Error ? e.message : String(e));
      })
      .finally(() => {
        if (!cancelled) setLoadingStops(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  // 2) Whenever the selected stop changes, fetch its ETA predictions.
  //    Also re-fetch every minute so the data doesn't go stale during a demo.
  useEffect(() => {
    if (stopId === null) return;
    let cancelled = false;
    setLoadingEta(true);
    setError(null);

    const refetch = (): void => {
      getEta(stopId)
        .then((list) => {
          if (cancelled) return;
          setEta(list);
        })
        .catch((e: unknown) => {
          if (cancelled) return;
          setError(e instanceof Error ? e.message : String(e));
        })
        .finally(() => {
          if (!cancelled) setLoadingEta(false);
        });
    };

    refetch();
    const interval = window.setInterval(refetch, 60_000);
    return () => {
      cancelled = true;
      window.clearInterval(interval);
    };
  }, [stopId]);

  // 3) Derive the recommendation from the current ETA list.
  //    `recommend` is pure, so calling it directly inside the render body
  //    is fine — it's cheaper than memoising for an array of at most 3 items.
  const recommendation = recommend(eta);

  return (
    <section style={{ padding: '16px 24px', fontFamily: 'system-ui, sans-serif' }}>
      <h2 style={{ marginTop: 0 }}>🧍 Пассажир — ближайшие трамваи</h2>
      <p style={{ color: '#666', marginTop: 4 }}>
        Выберите остановку, чтобы увидеть прогноз прибытия и загрузки.
      </p>

      <label htmlFor="stop-select" style={{ display: 'block', marginTop: 16, fontWeight: 600 }}>
        Остановка
      </label>
      <select
        id="stop-select"
        value={stopId ?? ''}
        onChange={(e) => setStopId(Number(e.target.value))}
        disabled={loadingStops || stops.length === 0}
        style={{
          marginTop: 4,
          padding: '8px 12px',
          fontSize: 16,
          minWidth: 240,
          border: '1px solid #ccc',
          borderRadius: 4,
          background: '#fff',
        }}
      >
        {loadingStops && <option value="">Загрузка остановок…</option>}
        {!loadingStops && stops.length === 0 && <option value="">Нет остановок</option>}
        {stops.map((stop) => (
          <option key={stop.id} value={stop.id}>
            {stop.name}
          </option>
        ))}
      </select>

      {error && (
        <Alert severity="warning" icon="⚠️">
          Ошибка загрузки данных: {error}
        </Alert>
      )}

      {loadingEta && stopId !== null && <p style={{ color: '#666' }}>Загрузка прогнозов…</p>}

      {!loadingEta && stopId !== null && (
        <>
          {/* recommend() returns "no data" Recommendation when eta is empty,
              so we render the banner unconditionally for the selected stop. */}
          <Alert severity={recommendation.severity} icon={recommendation.emoji}>
            {recommendation.text}
          </Alert>

          {eta.length > 0 && (
            <>
              <div
                style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
                  gap: 12,
                  marginTop: 16,
                }}
              >
                {eta.map((tram, i) => (
                  // eta_min + route_id together are unique per stop in practice.
                  <EtaCard key={`${tram.route_id}-${tram.eta_min}-${i}`} tram={tram} />
                ))}
              </div>

              <p style={{ marginTop: 16, color: '#888', fontSize: 12 }}>
                Модель: <code>{eta[0]?.model_id ?? '—'}</code> · обновлено только что
              </p>
            </>
          )}
        </>
      )}
    </section>
  );
}
